// Vollständige Liste der Hochschulen in Deutschland
// Quelle: https://de.wikipedia.org/wiki/Liste_der_Hochschulen_in_Deutschland
// Logos via Google Favicon API: https://www.google.com/s2/favicons?domain=...&sz=64
// Gefiltert: ohne Kunst-/Musik-/Theologische-/Polizei-/Verwaltungshochschulen

const KNOWN_DOMAINS = {
  // ── Bayern ─────────────────────────────────────────────────────────────
  'Technische Universität München': 'tum.de',
  'Ludwig-Maximilians-Universität München': 'lmu.de',
  'Friedrich-Alexander-Universität Erlangen-Nürnberg': 'fau.de',
  'Universität Augsburg': 'uni-augsburg.de',
  'Universität Bayreuth': 'uni-bayreuth.de',
  'Universität Passau': 'uni-passau.de',
  'Universität Regensburg': 'uni-regensburg.de',
  'Julius-Maximilians-Universität Würzburg': 'uni-wuerzburg.de',
  'Universität Bamberg': 'uni-bamberg.de',
  'Universität Eichstätt-Ingolstadt': 'ku.de',
  'Hochschule München': 'hm.edu',
  'Technische Hochschule Augsburg': 'tha.de',
  'Technische Hochschule Aschaffenburg': 'th-ab.de',
  'Technische Hochschule Deggendorf': 'th-deg.de',
  'Technische Hochschule Ingolstadt': 'thi.de',
  'Technische Hochschule Nürnberg': 'th-nuernberg.de',
  'Ostbayerische Technische Hochschule Amberg-Weiden': 'oth-aw.de',
  'Ostbayerische Technische Hochschule Regensburg': 'oth-regensburg.de',
  'Hochschule für angewandte Wissenschaften Coburg': 'hs-coburg.de',
  'Hochschule für angewandte Wissenschaften Ansbach': 'hs-ansbach.de',
  'Hochschule für angewandte Wissenschaften Kempten': 'hs-kempten.de',
  'Hochschule für angewandte Wissenschaften Landshut': 'haw-landshut.de',
  'Hochschule für angewandte Wissenschaften Rosenheim': 'fh-rosenheim.de',
  'Hochschule Weihenstephan-Triesdorf': 'hswt.de',

  // ── Baden-Württemberg ──────────────────────────────────────────────────
  'Karlsruher Institut für Technologie': 'kit.edu',
  'Universität Stuttgart': 'uni-stuttgart.de',
  'Universität Heidelberg': 'uni-heidelberg.de',
  'Albert-Ludwigs-Universität Freiburg im Breisgau': 'uni-freiburg.de',
  'Eberhard Karls Universität Tübingen': 'uni-tuebingen.de',
  'Universität Konstanz': 'uni-konstanz.de',
  'Universität Mannheim': 'uni-mannheim.de',
  'Universität Ulm': 'uni-ulm.de',
  'Hochschule Heilbronn': 'hs-heilbronn.de',
  'Hochschule Karlsruhe': 'h-ka.de',
  'Hochschule Mannheim': 'hs-mannheim.de',
  'Hochschule Pforzheim': 'hs-pforzheim.de',
  'Hochschule Esslingen': 'hs-esslingen.de',
  'Hochschule Reutlingen': 'reutlingen-university.de',
  'Hochschule Aalen': 'hs-aalen.de',
  'Hochschule Ulm': 'hs-ulm.de',
  'Hochschule Albstadt-Sigmaringen': 'hs-albsig.de',
  'Hochschule Furtwangen': 'hs-furtwangen.de',
  'Hochschule Offenburg': 'hs-offenburg.de',
  'Hochschule Biberach': 'hochschule-biberach.de',
  'Hochschule für Technik Stuttgart': 'hft-stuttgart.de',
  'DHBW Stuttgart': 'dhbw-stuttgart.de',
  'DHBW Mannheim': 'dhbw-mannheim.de',
  'DHBW Karlsruhe': 'dhbw-karlsruhe.de',
  'DHBW Mosbach': 'dhbw-mosbach.de',
  'DHBW Ravensburg': 'dhbw-ravensburg.de',
  'DHBW Villingen-Schwenningen': 'dhbw-vs.de',
  'DHBW Heidenheim': 'dhbw-heidenheim.de',
  'DHBW Lörrach': 'dhbw-loerrach.de',
  'Pädagogische Hochschule Freiburg': 'ph-freiburg.de',
  'Pädagogische Hochschule Heidelberg': 'ph-heidelberg.de',
  'Pädagogische Hochschule Karlsruhe': 'ph-karlsruhe.de',
  'Pädagogische Hochschule Ludwigsburg': 'ph-ludwigsburg.de',
  'Pädagogische Hochschule Schwäbisch Gmünd': 'ph-gmuend.de',

  // ── NRW ───────────────────────────────────────────────────────────────
  'Rheinisch-Westfälische Technische Hochschule Aachen': 'rwth-aachen.de',
  'Ruhr-Universität Bochum': 'ruhr-uni-bochum.de',
  'Technische Universität Dortmund': 'tu-dortmund.de',
  'Universität zu Köln': 'uni-koeln.de',
  'Rheinische Friedrich-Wilhelms-Universität Bonn': 'uni-bonn.de',
  'Westfälische Wilhelms-Universität Münster': 'uni-muenster.de',
  'Universität Duisburg-Essen': 'uni-due.de',
  'Universität Bielefeld': 'uni-bielefeld.de',
  'Heinrich-Heine-Universität Düsseldorf': 'hhu.de',
  'Bergische Universität Wuppertal': 'uni-wuppertal.de',
  'Universität Siegen': 'uni-siegen.de',
  'Universität Paderborn': 'uni-paderborn.de',
  'Universität zu Lübeck': 'uni-luebeck.de',
  'FernUniversität in Hagen': 'fernuni-hagen.de',
  'Fachhochschule Aachen': 'fh-aachen.de',
  'Fachhochschule Dortmund': 'fh-dortmund.de',
  'TH Köln': 'th-koeln.de',
  'Hochschule Bielefeld': 'hsbi.de',
  'Hochschule Bochum': 'hs-bochum.de',
  'Hochschule Düsseldorf': 'hs-duesseldorf.de',
  'Hochschule Hamm-Lippstadt': 'hshl.de',
  'Hochschule Rhein-Waal': 'hochschule-rhein-waal.de',
  'Hochschule Ruhr West': 'hochschule-ruhr-west.de',
  'Hochschule Bonn-Rhein-Sieg': 'h-brs.de',
  'Hochschule Niederrhein': 'hs-niederrhein.de',
  'Westfälische Hochschule': 'w-hs.de',

  // ── Berlin ────────────────────────────────────────────────────────────
  'Technische Universität Berlin': 'tu-berlin.de',
  'Freie Universität Berlin': 'fu-berlin.de',
  'Humboldt-Universität zu Berlin': 'hu-berlin.de',
  'Berliner Hochschule für Technik': 'bht-berlin.de',
  'Hochschule für Technik und Wirtschaft Berlin': 'htw-berlin.de',
  'Hochschule für Wirtschaft und Recht Berlin': 'hwr-berlin.de',

  // ── Hamburg ───────────────────────────────────────────────────────────
  'Universität Hamburg': 'uni-hamburg.de',
  'Technische Universität Hamburg': 'tuhh.de',
  'Hochschule für Angewandte Wissenschaften Hamburg': 'haw-hamburg.de',
  'HafenCity Universität Hamburg': 'hcu-hamburg.de',

  // ── Hessen ────────────────────────────────────────────────────────────
  'Technische Universität Darmstadt': 'tu-darmstadt.de',
  'Johann Wolfgang Goethe-Universität Frankfurt am Main': 'uni-frankfurt.de',
  'Philipps-Universität Marburg': 'uni-marburg.de',
  'Justus-Liebig-Universität Gießen': 'uni-giessen.de',
  'Universität Kassel': 'uni-kassel.de',
  'Hochschule Darmstadt': 'h-da.de',
  'Frankfurt University of Applied Sciences': 'frankfurt-university.de',
  'Hochschule Fulda': 'hs-fulda.de',
  'Hochschule RheinMain': 'hs-rm.de',
  'Hochschule Geisenheim': 'hs-gm.de',

  // ── Niedersachsen & Bremen ─────────────────────────────────────────────
  'Leibniz Universität Hannover': 'uni-hannover.de',
  'Technische Universität Carolo-Wilhelmina zu Braunschweig': 'tu-braunschweig.de',
  'Georg-August-Universität Göttingen': 'uni-goettingen.de',
  'Universität Osnabrück': 'uni-osnabrueck.de',
  'Carl von Ossietzky Universität Oldenburg': 'uni-oldenburg.de',
  'Universität Hildesheim': 'uni-hildesheim.de',
  'Technische Universität Clausthal': 'tu-clausthal.de',
  'Leuphana Universität Lüneburg': 'leuphana.de',
  'Hochschule Hannover': 'hs-hannover.de',
  'Hochschule Osnabrück': 'hs-osnabrueck.de',
  'Ostfalia Hochschule': 'ostfalia.de',
  'HAWK Hochschule Hildesheim/Holzminden/Göttingen': 'hawk.de',
  'Hochschule Emden/Leer': 'hs-emden-leer.de',
  'Universität Bremen': 'uni-bremen.de',
  'Hochschule Bremen': 'hs-bremen.de',
  'Hochschule Bremerhaven': 'hs-bremerhaven.de',

  // ── Sachsen ───────────────────────────────────────────────────────────
  'Technische Universität Dresden': 'tu-dresden.de',
  'Universität Leipzig': 'uni-leipzig.de',
  'Technische Universität Chemnitz': 'tu-chemnitz.de',
  'Technische Universität Bergakademie Freiberg': 'tu-freiberg.de',
  'Hochschule für Technik und Wirtschaft Dresden': 'htw-dresden.de',
  'Hochschule Mittweida': 'hs-mittweida.de',
  'Westsächsische Hochschule Zwickau': 'fh-zwickau.de',
  'Hochschule Zittau/Görlitz': 'hszg.de',

  // ── Thüringen ─────────────────────────────────────────────────────────
  'Friedrich-Schiller-Universität Jena': 'uni-jena.de',
  'Technische Universität Ilmenau': 'tu-ilmenau.de',
  'Universität Erfurt': 'uni-erfurt.de',
  'Ernst-Abbe-Hochschule Jena': 'eah-jena.de',
  'Fachhochschule Erfurt': 'fh-erfurt.de',

  // ── Sachsen-Anhalt ────────────────────────────────────────────────────
  'Martin-Luther-Universität Halle-Wittenberg': 'uni-halle.de',
  'Otto-von-Guericke-Universität Magdeburg': 'ovgu.de',
  'Hochschule Anhalt': 'hs-anhalt.de',
  'Hochschule Harz': 'hs-harz.de',
  'Hochschule Merseburg': 'hs-merseburg.de',

  // ── Mecklenburg-Vorpommern ────────────────────────────────────────────
  'Universität Rostock': 'uni-rostock.de',
  'Ernst-Moritz-Arndt-Universität Greifswald': 'uni-greifswald.de',
  'Hochschule Wismar': 'hs-wismar.de',
  'Hochschule Stralsund': 'hochschule-stralsund.de',
  'Hochschule Neubrandenburg': 'hs-nb.de',

  // ── Schleswig-Holstein ────────────────────────────────────────────────
  'Universität zu Kiel': 'uni-kiel.de',
  'Universität zu Lübeck': 'uni-luebeck.de',
  'Europa-Universität Flensburg': 'uni-flensburg.de',
  'Hochschule Flensburg': 'hs-flensburg.de',
  'Fachhochschule Kiel': 'fh-kiel.de',
  'Fachhochschule Lübeck': 'fh-luebeck.de',

  // ── Rheinland-Pfalz ───────────────────────────────────────────────────
  'Johannes Gutenberg-Universität Mainz': 'uni-mainz.de',
  'RPTU Kaiserslautern-Landau': 'rptu.de',
  'Universität Trier': 'uni-trier.de',
  'Universität Koblenz': 'uni-koblenz.de',
  'Hochschule Koblenz': 'hs-koblenz.de',
  'Hochschule Trier': 'hochschule-trier.de',
  'Hochschule Mainz': 'hs-mainz.de',
  'Hochschule Kaiserslautern': 'hs-kl.de',
  'Hochschule Worms': 'hs-worms.de',
  'Technische Hochschule Bingen': 'th-bingen.de',

  // ── Saarland ──────────────────────────────────────────────────────────
  'Universität des Saarlandes': 'uni-saarland.de',
  'htw saar': 'htwsaar.de',

  // ── Brandenburg ───────────────────────────────────────────────────────
  'Brandenburgische Technische Universität Cottbus-Senftenberg': 'b-tu.de',
  'Technische Hochschule Brandenburg': 'th-brandenburg.de',
  'Fachhochschule Potsdam': 'fh-potsdam.de',
  'Universität Potsdam': 'uni-potsdam.de',
  'Hochschule für nachhaltige Entwicklung Eberswalde': 'hnee.de',
  'Europa-Universität Viadrina Frankfurt (Oder)': 'europa-uni.de',
};

// Alle Hochschulen (Name + Stadt), gefiltert nach Relevanz für Technik/Wirtschaft
const RAW_LIST = [
  // A
  { name: 'Fachhochschule Aachen', city: 'Aachen' },
  { name: 'Rheinisch-Westfälische Technische Hochschule Aachen', city: 'Aachen' },
  { name: 'Hochschule Aalen', city: 'Aalen' },
  { name: 'Hochschule Albstadt-Sigmaringen', city: 'Albstadt' },
  { name: 'Ostbayerische Technische Hochschule Amberg-Weiden', city: 'Amberg' },
  { name: 'Hochschule Anhalt', city: 'Köthen' },
  { name: 'Hochschule für angewandte Wissenschaften Ansbach', city: 'Ansbach' },
  { name: 'Technische Hochschule Aschaffenburg', city: 'Aschaffenburg' },
  { name: 'Technische Hochschule Augsburg', city: 'Augsburg' },
  { name: 'Universität Augsburg', city: 'Augsburg' },
  // B
  { name: 'Universität Bamberg', city: 'Bamberg' },
  { name: 'Universität Bayreuth', city: 'Bayreuth' },
  { name: 'Berliner Hochschule für Technik', city: 'Berlin' },
  { name: 'Freie Universität Berlin', city: 'Berlin' },
  { name: 'Hochschule für Technik und Wirtschaft Berlin', city: 'Berlin' },
  { name: 'Hochschule für Wirtschaft und Recht Berlin', city: 'Berlin' },
  { name: 'Humboldt-Universität zu Berlin', city: 'Berlin' },
  { name: 'Technische Universität Berlin', city: 'Berlin' },
  { name: 'Hochschule Biberach', city: 'Biberach' },
  { name: 'Hochschule Bielefeld', city: 'Bielefeld' },
  { name: 'Universität Bielefeld', city: 'Bielefeld' },
  { name: 'Technische Hochschule Bingen', city: 'Bingen' },
  { name: 'Hochschule Bochum', city: 'Bochum' },
  { name: 'Ruhr-Universität Bochum', city: 'Bochum' },
  { name: 'Hochschule Bonn-Rhein-Sieg', city: 'Sankt Augustin' },
  { name: 'Rheinische Friedrich-Wilhelms-Universität Bonn', city: 'Bonn' },
  { name: 'Technische Hochschule Brandenburg', city: 'Brandenburg' },
  { name: 'Technische Universität Carolo-Wilhelmina zu Braunschweig', city: 'Braunschweig' },
  { name: 'Hochschule Bremen', city: 'Bremen' },
  { name: 'Universität Bremen', city: 'Bremen' },
  { name: 'Hochschule Bremerhaven', city: 'Bremerhaven' },
  // C
  { name: 'Technische Universität Chemnitz', city: 'Chemnitz' },
  { name: 'Technische Universität Clausthal', city: 'Clausthal-Zellerfeld' },
  { name: 'Hochschule für angewandte Wissenschaften Coburg', city: 'Coburg' },
  { name: 'Brandenburgische Technische Universität Cottbus-Senftenberg', city: 'Cottbus' },
  // D
  { name: 'Hochschule Darmstadt', city: 'Darmstadt' },
  { name: 'Technische Universität Darmstadt', city: 'Darmstadt' },
  { name: 'Technische Hochschule Deggendorf', city: 'Deggendorf' },
  { name: 'Fachhochschule Dortmund', city: 'Dortmund' },
  { name: 'Technische Universität Dortmund', city: 'Dortmund' },
  { name: 'Hochschule für Technik und Wirtschaft Dresden', city: 'Dresden' },
  { name: 'Technische Universität Dresden', city: 'Dresden' },
  { name: 'Universität Duisburg-Essen', city: 'Duisburg / Essen' },
  { name: 'Hochschule Düsseldorf', city: 'Düsseldorf' },
  { name: 'Heinrich-Heine-Universität Düsseldorf', city: 'Düsseldorf' },
  // E
  { name: 'Hochschule für nachhaltige Entwicklung Eberswalde', city: 'Eberswalde' },
  { name: 'Universität Eichstätt-Ingolstadt', city: 'Eichstätt' },
  { name: 'Hochschule Emden/Leer', city: 'Emden' },
  { name: 'Fachhochschule Erfurt', city: 'Erfurt' },
  { name: 'Universität Erfurt', city: 'Erfurt' },
  { name: 'Friedrich-Alexander-Universität Erlangen-Nürnberg', city: 'Erlangen / Nürnberg' },
  { name: 'Hochschule Esslingen', city: 'Esslingen' },
  // F
  { name: 'Hochschule Flensburg', city: 'Flensburg' },
  { name: 'Europa-Universität Flensburg', city: 'Flensburg' },
  { name: 'Frankfurt University of Applied Sciences', city: 'Frankfurt am Main' },
  { name: 'Johann Wolfgang Goethe-Universität Frankfurt am Main', city: 'Frankfurt am Main' },
  { name: 'Europa-Universität Viadrina Frankfurt (Oder)', city: 'Frankfurt (Oder)' },
  { name: 'Albert-Ludwigs-Universität Freiburg im Breisgau', city: 'Freiburg' },
  { name: 'Technische Universität Bergakademie Freiberg', city: 'Freiberg' },
  { name: 'Pädagogische Hochschule Freiburg', city: 'Freiburg' },
  { name: 'Hochschule Fulda', city: 'Fulda' },
  { name: 'Hochschule Furtwangen', city: 'Furtwangen' },
  // G
  { name: 'Hochschule Geisenheim', city: 'Geisenheim' },
  { name: 'Justus-Liebig-Universität Gießen', city: 'Gießen' },
  { name: 'Georg-August-Universität Göttingen', city: 'Göttingen' },
  { name: 'Universität Greifswald', city: 'Greifswald' },
  // H
  { name: 'FernUniversität in Hagen', city: 'Hagen' },
  { name: 'Martin-Luther-Universität Halle-Wittenberg', city: 'Halle' },
  { name: 'HafenCity Universität Hamburg', city: 'Hamburg' },
  { name: 'Hochschule für Angewandte Wissenschaften Hamburg', city: 'Hamburg' },
  { name: 'Technische Universität Hamburg', city: 'Hamburg' },
  { name: 'Universität Hamburg', city: 'Hamburg' },
  { name: 'Hochschule Hamm-Lippstadt', city: 'Hamm' },
  { name: 'Hochschule Hannover', city: 'Hannover' },
  { name: 'Leibniz Universität Hannover', city: 'Hannover' },
  { name: 'Hochschule Harz', city: 'Wernigerode' },
  { name: 'HAWK Hochschule Hildesheim/Holzminden/Göttingen', city: 'Hildesheim' },
  { name: 'Universität Hildesheim', city: 'Hildesheim' },
  { name: 'Hochschule Heilbronn', city: 'Heilbronn' },
  { name: 'DHBW Heidenheim', city: 'Heidenheim' },
  // I
  { name: 'Technische Hochschule Ingolstadt', city: 'Ingolstadt' },
  // J
  { name: 'Friedrich-Schiller-Universität Jena', city: 'Jena' },
  { name: 'Ernst-Abbe-Hochschule Jena', city: 'Jena' },
  // K
  { name: 'Karlsruher Institut für Technologie', city: 'Karlsruhe' },
  { name: 'Hochschule Karlsruhe', city: 'Karlsruhe' },
  { name: 'DHBW Karlsruhe', city: 'Karlsruhe' },
  { name: 'Universität Kassel', city: 'Kassel' },
  { name: 'Hochschule Kaiserslautern', city: 'Kaiserslautern' },
  { name: 'RPTU Kaiserslautern-Landau', city: 'Kaiserslautern' },
  { name: 'Hochschule für angewandte Wissenschaften Kempten', city: 'Kempten' },
  { name: 'Universität zu Kiel', city: 'Kiel' },
  { name: 'Fachhochschule Kiel', city: 'Kiel' },
  { name: 'Universität Koblenz', city: 'Koblenz' },
  { name: 'Hochschule Koblenz', city: 'Koblenz' },
  { name: 'TH Köln', city: 'Köln' },
  { name: 'Universität zu Köln', city: 'Köln' },
  { name: 'Universität Konstanz', city: 'Konstanz' },
  // L
  { name: 'Hochschule für angewandte Wissenschaften Landshut', city: 'Landshut' },
  { name: 'Universität Leipzig', city: 'Leipzig' },
  { name: 'DHBW Lörrach', city: 'Lörrach' },
  { name: 'Fachhochschule Lübeck', city: 'Lübeck' },
  { name: 'Universität zu Lübeck', city: 'Lübeck' },
  { name: 'Leuphana Universität Lüneburg', city: 'Lüneburg' },
  { name: 'Ludwig-Maximilians-Universität München', city: 'München' },
  // M
  { name: 'Otto-von-Guericke-Universität Magdeburg', city: 'Magdeburg' },
  { name: 'Johannes Gutenberg-Universität Mainz', city: 'Mainz' },
  { name: 'Hochschule Mainz', city: 'Mainz' },
  { name: 'Universität Mannheim', city: 'Mannheim' },
  { name: 'Hochschule Mannheim', city: 'Mannheim' },
  { name: 'DHBW Mannheim', city: 'Mannheim' },
  { name: 'Philipps-Universität Marburg', city: 'Marburg' },
  { name: 'Hochschule Merseburg', city: 'Merseburg' },
  { name: 'Hochschule Mittweida', city: 'Mittweida' },
  { name: 'DHBW Mosbach', city: 'Mosbach' },
  { name: 'Hochschule München', city: 'München' },
  { name: 'Technische Universität München', city: 'München' },
  { name: 'Westfälische Wilhelms-Universität Münster', city: 'Münster' },
  // N
  { name: 'Hochschule Neubrandenburg', city: 'Neubrandenburg' },
  { name: 'Hochschule Niederrhein', city: 'Krefeld / Mönchengladbach' },
  { name: 'Technische Hochschule Nürnberg', city: 'Nürnberg' },
  // O
  { name: 'Carl von Ossietzky Universität Oldenburg', city: 'Oldenburg' },
  { name: 'Universität Osnabrück', city: 'Osnabrück' },
  { name: 'Hochschule Osnabrück', city: 'Osnabrück' },
  { name: 'Ostfalia Hochschule', city: 'Wolfenbüttel' },
  // P
  { name: 'Universität Paderborn', city: 'Paderborn' },
  { name: 'Universität Passau', city: 'Passau' },
  { name: 'Hochschule Pforzheim', city: 'Pforzheim' },
  { name: 'Fachhochschule Potsdam', city: 'Potsdam' },
  { name: 'Universität Potsdam', city: 'Potsdam' },
  // R
  { name: 'DHBW Ravensburg', city: 'Ravensburg' },
  { name: 'Ostbayerische Technische Hochschule Regensburg', city: 'Regensburg' },
  { name: 'Universität Regensburg', city: 'Regensburg' },
  { name: 'Hochschule Reutlingen', city: 'Reutlingen' },
  { name: 'Hochschule Rhein-Waal', city: 'Kleve' },
  { name: 'Hochschule RheinMain', city: 'Wiesbaden' },
  { name: 'Hochschule Ruhr West', city: 'Mülheim an der Ruhr' },
  { name: 'Universität Rostock', city: 'Rostock' },
  { name: 'Hochschule Wismar', city: 'Wismar' },
  // S
  { name: 'Universität des Saarlandes', city: 'Saarbrücken' },
  { name: 'htw saar', city: 'Saarbrücken' },
  { name: 'Hochschule Hochschule Stralsund', city: 'Stralsund' },
  { name: 'Hochschule für Technik Stuttgart', city: 'Stuttgart' },
  { name: 'DHBW Stuttgart', city: 'Stuttgart' },
  { name: 'Universität Stuttgart', city: 'Stuttgart' },
  // T
  { name: 'Universität Trier', city: 'Trier' },
  { name: 'Hochschule Trier', city: 'Trier' },
  { name: 'Eberhard Karls Universität Tübingen', city: 'Tübingen' },
  // U
  { name: 'Universität Ulm', city: 'Ulm' },
  { name: 'Hochschule Ulm', city: 'Ulm' },
  // V
  { name: 'DHBW Villingen-Schwenningen', city: 'Villingen-Schwenningen' },
  // W
  { name: 'Westfälische Hochschule', city: 'Gelsenkirchen' },
  { name: 'Hochschule Weihenstephan-Triesdorf', city: 'Freising' },
  { name: 'Bergische Universität Wuppertal', city: 'Wuppertal' },
  { name: 'Julius-Maximilians-Universität Würzburg', city: 'Würzburg' },
  { name: 'Hochschule Worms', city: 'Worms' },
  // Z
  { name: 'Westsächsische Hochschule Zwickau', city: 'Zwickau' },
  { name: 'Hochschule Zittau/Görlitz', city: 'Zittau' },
];

// Attach domains and sort alphabetically
export const GERMAN_UNIVERSITIES = RAW_LIST
  .map(u => ({ ...u, domain: KNOWN_DOMAINS[u.name] || null }))
  .sort((a, b) => a.name.localeCompare(b.name, 'de'));

export function getLogoUrl(domain) {
  if (!domain) return null;
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`;
}

export function findUniversity(name) {
  return GERMAN_UNIVERSITIES.find(u => u.name === name) || null;
}
